name: Keep ScreenerPro Sites Awake

on:
  schedule:
    - cron: "*/45 * * * *"  # Every 45 minutes
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests module
        run: pip install requests

      - name: Run keep_alive.py
        run: python keep_alive.py
